__title__ = 'FasterRunner'
__description__ = 'A tool for HTTP(S) testing.'
__url__ = 'https://github.com/yinquanwang/FasterRunner'
__version__ = '1.0'
__author__ = 'yinquanwang'
__author_email__ = 'm17602144093@163.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 yinquanwang'