# Generated by Django 2.1.3 on 2019-01-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fastrunner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='任务名称')),
                ('identity', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('send_type', models.IntegerField(choices=[(1, '不发送结果'), (2, '失败后发送'), (3, '始终发送')], default=3, verbose_name='发送策略')),
                ('config', models.TextField(verbose_name='任务配置')),
                ('receiver', models.CharField(max_length=2048, null=True, verbose_name='接收者')),
                ('copy', models.CharField(max_length=2048, null=True, verbose_name='抄送者')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastrunner.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '定时任务',
                'db_table': 'Schedule',
            },
        ),
    ]
