# Generated by Django 2.1 on 2018-08-27 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='登陆密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='用户邮箱')),
            ],
            options={
                'verbose_name': '用户信息',
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.CharField(choices=[(1, 'admin'), (2, 'read'), (3, 'write'), (4, 'delete')], max_length=50, verbose_name='项目权限')),
                ('api', models.CharField(choices=[(1, 'admin'), (2, 'read'), (3, 'write'), (4, 'delete')], max_length=200, verbose_name='接口权限')),
                ('suite', models.CharField(choices=[(1, 'admin'), (2, 'read'), (3, 'write'), (4, 'delete')], max_length=200, verbose_name='suite权限')),
                ('test', models.CharField(choices=[(1, 'admin'), (2, 'read'), (3, 'write'), (4, 'delete')], max_length=200, verbose_name='用例权限')),
                ('config', models.CharField(choices=[(1, 'admin'), (2, 'read'), (3, 'write'), (4, 'delete')], max_length=200, verbose_name='配置权限')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermanager.UserInfo')),
            ],
            options={
                'verbose_name': '用户权限管理',
                'db_table': 'UserPermission',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('token', models.CharField(max_length=50, verbose_name='token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermanager.UserInfo')),
            ],
            options={
                'verbose_name': '用户登陆token',
                'db_table': 'UserToken',
            },
        ),
    ]
