# Generated by Django 2.1.3 on 2019-07-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fastuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='level',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, '管理员')], default=0, verbose_name='用户等级'),
        ),
    ]
