# Generated by Django 2.1.11 on 2020-08-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastuser', '0002_auto_20200509_1122'),
        ('fastuser', '0002_auto_20200428_0124'),
    ]

    operations = [
    ]
