# Generated by Django 2.2 on 2020-09-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fastuser", "0004_auto_20200814_1605"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="phone",
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name="手机号码"),
        ),
    ]
