# Generated by Django 4.1.13 on 2024-03-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fastuser", "0006_myuser_show_hosts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
