# Generated by Django 2.1 on 2018-08-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='tree',
            field=models.TextField(default=[], verbose_name='结构主题'),
        ),
    ]
