# Generated by Django 2.1.3 on 2019-05-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='delete',
            field=models.IntegerField(null=True, verbose_name='是否删除'),
        ),
    ]
