# Generated by Django 2.1.3 on 2018-12-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0002_auto_20181205_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='body',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='report',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='report',
            name='failure',
        ),
        migrations.RemoveField(
            model_name='report',
            name='skipped',
        ),
        migrations.RemoveField(
            model_name='report',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='report',
            name='success',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total',
        ),
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.IntegerField(choices=[(1, '调试用例报告'), (2, '异步任务报告'), (3, '定时任务报告')], default=1, verbose_name='报告类型'),
            preserve_default=False,
        ),
    ]
