# Generated by Django 2.1 on 2018-08-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0002_auto_20180827_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBinary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件名称')),
                ('body', models.BinaryField(verbose_name='二进制流')),
                ('type', models.IntegerField(verbose_name='类型')),
                ('relation', models.IntegerField(verbose_name='关联ID')),
            ],
            options={
                'verbose_name': '二进制文件',
                'db_table': 'FileBinary',
            },
        ),
    ]
