# Generated by Django 2.1.3 on 2019-05-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0002_api_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='rig_id',
            field=models.IntegerField(null=True, verbose_name='网关API_id'),
        ),
    ]
