# Generated by Django 2.1.11 on 2020-08-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0003_casestep_source_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='creator',
            field=models.CharField(max_length=20, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='api',
            name='updater',
            field=models.CharField(max_length=20, null=True, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='case',
            name='creator',
            field=models.CharField(max_length=20, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='case',
            name='updater',
            field=models.CharField(max_length=20, null=True, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='casestep',
            name='creator',
            field=models.CharField(max_length=20, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='casestep',
            name='updater',
            field=models.CharField(max_length=20, null=True, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='config',
            name='creator',
            field=models.CharField(max_length=20, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='config',
            name='updater',
            field=models.CharField(max_length=20, null=True, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='hostip',
            name='creator',
            field=models.CharField(max_length=20, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='hostip',
            name='updater',
            field=models.CharField(max_length=20, null=True, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.CharField(max_length=20, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='project',
            name='updater',
            field=models.CharField(max_length=20, null=True, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='report',
            name='creator',
            field=models.CharField(max_length=20, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='report',
            name='updater',
            field=models.CharField(max_length=20, null=True, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='variables',
            name='creator',
            field=models.CharField(max_length=20, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='variables',
            name='updater',
            field=models.CharField(max_length=20, null=True, verbose_name='更新人'),
        ),
    ]
