# Generated by Django 2.1 on 2018-09-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0003_filebinary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='body',
        ),
        migrations.RemoveField(
            model_name='case',
            name='method',
        ),
        migrations.RemoveField(
            model_name='case',
            name='url',
        ),
        migrations.RemoveField(
            model_name='suite',
            name='suite',
        ),
        migrations.AddField(
            model_name='filebinary',
            name='size',
            field=models.IntegerField(default=0, verbose_name='大小'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='api',
            name='url',
            field=models.CharField(max_length=100, verbose_name='请求地址'),
        ),
        migrations.AlterField(
            model_name='casestep',
            name='url',
            field=models.CharField(max_length=100, verbose_name='请求地址'),
        ),
        migrations.AlterField(
            model_name='config',
            name='base_url',
            field=models.CharField(max_length=100, verbose_name='请求地址'),
        ),
        migrations.AlterField(
            model_name='config',
            name='method',
            field=models.CharField(max_length=10, null=True, verbose_name='请求方式'),
        ),
        migrations.AlterField(
            model_name='database',
            name='desc',
            field=models.CharField(max_length=50, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='database',
            name='server',
            field=models.CharField(max_length=100, verbose_name='服务地址'),
        ),
        migrations.AlterField(
            model_name='filebinary',
            name='name',
            field=models.CharField(max_length=50, verbose_name='文件名称'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='type',
            field=models.IntegerField(default=1, verbose_name='树类型'),
        ),
        migrations.AlterField(
            model_name='report',
            name='duration',
            field=models.CharField(max_length=40, verbose_name='持续时间'),
        ),
        migrations.AlterField(
            model_name='suite',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Suite名称'),
        ),
        migrations.AlterField(
            model_name='suitestep',
            name='name',
            field=models.CharField(max_length=50, verbose_name='API名称'),
        ),
        migrations.AlterField(
            model_name='suitestep',
            name='url',
            field=models.CharField(max_length=100, verbose_name='请求地址'),
        ),
    ]
