# Generated by Django 2.1.3 on 2019-05-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0003_api_rig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='rig_id',
            field=models.IntegerField(db_index=True, null=True, verbose_name='网关API_id'),
        ),
    ]
