# Generated by Django 2.1.3 on 2019-01-03 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0004_report_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name': '全局变量',
                'db_table': 'Variables',
            },
        ),
        migrations.AlterField(
            model_name='api',
            name='url',
            field=models.CharField(max_length=200, verbose_name='请求地址'),
        ),
        migrations.AlterField(
            model_name='casestep',
            name='url',
            field=models.CharField(max_length=200, verbose_name='请求地址'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='variables',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastrunner.Project'),
        ),
    ]
