# Generated by Django 2.1 on 2018-09-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0004_auto_20180904_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suite',
            name='project',
        ),
        migrations.RemoveField(
            model_name='suitestep',
            name='suite',
        ),
        migrations.DeleteModel(
            name='Suite',
        ),
        migrations.DeleteModel(
            name='SuiteStep',
        ),
    ]
