# Generated by Django 2.1.3 on 2019-06-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0004_auto_20190527_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='rig_env',
            field=models.IntegerField(choices=[(0, '测试环境'), (1, '生产环境'), (2, '预发布 ')], db_index=True, default=0, verbose_name='网关环境'),
        ),
    ]
