# Generated by Django 2.1 on 2018-09-05 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0005_auto_20180905_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastrunner.Project'),
        ),
    ]
