# Generated by Django 2.2 on 2020-08-22 09:52

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fastrunner", "0005_auto_20200814_1728"),
    ]

    operations = [
        migrations.AddField(
            model_name="api",
            name="case_id",
            field=django_mysql.models.ListCharField(
                models.IntegerField(default=0, verbose_name="case_id"), default=[], max_length=5, size=500
            ),
            preserve_default=False,
        ),
    ]
