# Generated by Django 2.1.3 on 2019-07-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0005_api_rig_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='tag',
            field=models.IntegerField(choices=[(0, '未调试'), (1, '调试成功'), (2, '调试失败')], db_index=True, default=0, verbose_name='API标签'),
        ),
    ]
