# Generated by Django 2.2 on 2020-08-22 11:19

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0006_api_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='case_id',
            field=django_mysql.models.ListCharField(models.IntegerField(default=0, verbose_name='case_id'), max_length=1000, size=500),
        ),
    ]
