# Generated by Django 2.1.3 on 2019-11-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fastrunner', '0006_api_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='rig_env',
            field=models.IntegerField(choices=[(0, '测试环境'), (1, '生产环境'), (2, '预发布 ')], default=0, verbose_name='网关环境'),
        ),
        migrations.AlterField(
            model_name='api',
            name='tag',
            field=models.IntegerField(choices=[(0, '还未调试'), (1, '手动成功'), (2, '调试失败'), (3, '自动成功')], default=0,
                                      verbose_name='API标签'),
        ),
        migrations.AlterField(
            model_name='api',
            name='url',
            field=models.CharField(db_index=True, max_length=200, verbose_name='请求地址'),
        ),
    ]
