# Generated by Django 2.1 on 2018-09-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0006_auto_20180905_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='method',
        ),
        migrations.AlterField(
            model_name='config',
            name='body',
            field=models.TextField(default=[], verbose_name='主体信息'),
            preserve_default=False,
        ),
    ]
