# Generated by Django 2.1 on 2018-09-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0007_auto_20180914_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debugtalk',
            old_name='debugtalk',
            new_name='code',
        ),
    ]
