# Generated by Django 2.1.3 on 2019-11-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fastrunner', '0007_auto_20191113_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='接口名称'),
        ),
    ]
