# Generated by Django 2.1 on 2018-09-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0008_auto_20180920_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebinary',
            name='type',
            field=models.IntegerField(default=1, verbose_name='类型'),
        ),
    ]
