# Generated by Django 2.1.3 on 2019-11-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fastrunner', '0008_auto_20191113_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='delete',
            field=models.IntegerField(default=0, null=True, verbose_name='是否删除'),
        ),
    ]
