# Generated by Django 2.1.3 on 2019-11-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fastrunner', '0009_auto_20191113_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='全局变量描述'),
        ),
    ]
