# Generated by Django 2.2 on 2020-08-22 23:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fastrunner", "0009_auto_20200822_1206"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="apis",
        ),
    ]
