# Generated by Django 2.1.3 on 2019-12-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fastrunner', '0010_variables_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.IntegerField(choices=[(1, '调试'), (2, '异步'), (3, '定时'), (4, '部署')], verbose_name='报告类型'),
        ),
    ]
