# Generated by Django 2.2 on 2020-10-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fastrunner", "0010_remove_case_apis"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user", models.CharField(max_length=100, verbose_name="访问url的用户名")),
                ("url", models.CharField(max_length=100, verbose_name="被访问的url")),
                (
                    "request_method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                            ("OPTION", "OPTION"),
                        ],
                        max_length=7,
                        verbose_name="请求方法",
                    ),
                ),
                ("times", models.IntegerField(verbose_name="访问次数")),
            ],
            options={
                "db_table": "visit",
            },
        ),
        migrations.AlterField(
            model_name="api",
            name="tag",
            field=models.IntegerField(
                choices=[(0, "未知"), (1, "成功"), (2, "失败"), (3, "自动成功")], default=0, verbose_name="API标签"
            ),
        ),
    ]
