# Generated by Django 2.2 on 2020-10-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0012_auto_20201013_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=20, verbose_name='用户的ip'),
            preserve_default=False,
        ),
    ]
