# Generated by Django 2.1.3 on 2020-01-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('fastrunner', '0012_auto_20200107_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='summary_detail',
        ),
        migrations.AddField(
            model_name='reportdetail',
            name='report_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fastrunner.Report'),
        ),
    ]
