# Generated by Django 2.1.3 on 2020-01-20 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fastrunner', '0013_auto_20200120_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportdetail',
            old_name='report_id',
            new_name='report',
        ),
    ]
