# Generated by Django 2.1.3 on 2020-01-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fastrunner', '0014_auto_20200120_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='默认配置'),
        ),
    ]
