# Generated by Django 2.2 on 2020-04-23 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('fastrunner', '0016_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdetail',
            name='report',
            field=models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='fastrunner.Report'),
        ),
    ]
