# Generated by Django 2.2 on 2021-09-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fastrunner", "0022_auto_20210525_2145"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="jira_bearer_token",
            field=models.CharField(blank=True, default="", max_length=45, verbose_name="jira bearer_token"),
        ),
        migrations.AddField(
            model_name="project",
            name="jira_project_key",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="jira项目key"),
        ),
        migrations.AlterField(
            model_name="api",
            name="tag",
            field=models.IntegerField(
                choices=[(0, "未知"), (1, "成功"), (2, "失败"), (3, "自动成功"), (4, "废弃")],
                default=0,
                verbose_name="API标签",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="tag",
            field=models.IntegerField(
                choices=[(1, "冒烟用例"), (2, "集成用例"), (3, "监控脚本"), (4, "核心用例")],
                default=2,
                verbose_name="用例标签",
            ),
        ),
    ]
