# Generated by Django 3.2.15 on 2022-11-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastrunner', '0023_auto_20210910_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestep',
            name='source_api_id',
            field=models.IntegerField(default=0, verbose_name='api来源'),
        ),
    ]
