# Generated by Django 4.1.13 on 2024-03-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fastrunner", "0023_auto_20210910_1155"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_deleted",
            field=models.IntegerField(default=0, null=True, verbose_name="是否删除"),
        ),
    ]
