# Generated by Django 4.1.13 on 2024-02-25 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MockProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.CharField(max_length=20, null=True, verbose_name="创建人"),
                ),
                (
                    "updater",
                    models.CharField(max_length=20, null=True, verbose_name="更新人"),
                ),
                ("project_id", models.CharField(max_length=100, unique=True)),
                ("project_name", models.CharField(max_length=100)),
                ("project_desc", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "mock项目表",
                "db_table": "mock_project_tab",
                "unique_together": {("project_id",)},
            },
        ),
        migrations.CreateModel(
            name="MockAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.CharField(max_length=20, null=True, verbose_name="创建人"),
                ),
                (
                    "updater",
                    models.CharField(max_length=20, null=True, verbose_name="更新人"),
                ),
                ("request_path", models.CharField(max_length=100)),
                (
                    "request_method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                            ("PATCH", "PATCH"),
                        ],
                        default="GET",
                        max_length=10,
                    ),
                ),
                ("response_text", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mock.mockproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "mock接口表",
                "db_table": "mock_api_tab",
                "unique_together": {("project", "request_path", "request_method")},
            },
        ),
    ]
