# Generated by Django 4.1.13 on 2024-02-27 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mock", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mockapi",
            options={"ordering": ["-create_time"], "verbose_name": "mock接口表"},
        ),
        migrations.AlterField(
            model_name="mockapi",
            name="project",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="mock.mockproject",
                to_field="project_id",
            ),
        ),
    ]
