# Generated by Django 4.1.13 on 2024-03-02 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0003_mockapi_api_desc_mockapi_api_id_mockapi_api_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockapi',
            name='followers',
        ),
        migrations.AddField(
            model_name='mockapi',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mockapi',
            name='api_id',
            field=models.CharField(default='9b5855cb6dc945b1a7b8832d61a64069', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='mockapi',
            name='request_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='POST', max_length=10),
        ),
        migrations.CreateModel(
            name='MockAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('updater', models.CharField(max_length=20, null=True, verbose_name='更新人')),
                ('request_obj', models.JSONField(default=dict)),
                ('response_obj', models.JSONField(default=dict)),
                ('api', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='mock.mockapi', to_field='api_id')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mock_logs', to='mock.mockproject', to_field='project_id')),
            ],
            options={
                'verbose_name': 'mock api log表',
                'db_table': 'mock_api_log',
                'ordering': ['-create_time'],
            },
        ),
    ]
