# Generated by Django 4.1.13 on 2024-03-21 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mock", "0006_mockapi_request_body_mockapi_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MockAPIResponseHandler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.CharField(max_length=20, null=True, verbose_name="创建人"),
                ),
                (
                    "updater",
                    models.CharField(max_length=20, null=True, verbose_name="更新人"),
                ),
                (
                    "condition_expression",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="条件判断表达式"
                    ),
                ),
                (
                    "response_set_value_expression",
                    models.CharField(max_length=255, verbose_name="响应设置值表达式"),
                ),
                (
                    "response_set_value",
                    models.CharField(max_length=255, verbose_name="响应设置的值"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "api",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="response_handlers",
                        to="mock.mockapi",
                        to_field="api_id",
                    ),
                ),
            ],
            options={
                "verbose_name": "mock api response handler",
                "db_table": "mock_api_response_handler",
                "ordering": ["-create_time"],
            },
        ),
    ]
