# Generated by Django 4.1.13 on 2024-03-22 00:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mock", "0007_mockapiresponsehandler"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockapiresponsehandler",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="mockapiresponsehandler",
            name="name",
            field=models.CharField(
                db_index=True, default=django.utils.timezone.now, max_length=255
            ),
            preserve_default=False,
        ),
    ]
