name: check web pr

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.py'

jobs:
  build_web_image:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: rikasai
      DOCKER_REPOSITORY_NAME: fast-runner-frontend

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4


    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get Git tag if exists
      id: get_tag
      run: |
        GIT_TAG=$(git describe --tags --exact-match ${{ github.sha }} 2> /dev/null || echo "")
        echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV

    - name: Build Image
      uses: docker/build-push-action@v5
      with:
        context: ./web
        file: ./web/Dockerfile-build
        platforms: linux/amd64
        push: false
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPOSITORY_NAME }}:latest
          ${{ env.GIT_TAG != '' && format('{0}/{1}:{2}', env.DOCKERHUB_USERNAME, env.DOCKER_REPOSITORY_NAME, env.GIT_TAG) || '' }}
