name: Build and Upload Web dist
on:
  workflow_dispatch:
  release:
    types: [ released ]
  pull_request:
    paths:
      - 'web/**'
      - '!web/dist/**'
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        cd web
        yarn install
    - name: Build
      run: |
        cd web
        npm run build
    - name: Upload Files
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: web/dist
