FROM node:22 as build-stage

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
# RUN yarn install --registry https://registry.npm.taobao.org/
RUN yarn install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

#ENV NODE_OPTIONS="--max_old_space_size=2048"
#ARG API_URL="http://119.91.147.215:8000"
#ENV API_URL=$API_URL
#ENV FasterRunner="myFasterRunner"
# build app for production with minification

RUN npm run build

FROM nginx:1.21-alpine

RUN rm /etc/nginx/conf.d/default.conf

RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
